spring.datasource:
  url: jdbc:mysql://localhost:3307/testa?useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver

# HikariCP settings
spring.datasource.hikari:
  #60 sec
  connection-timeout: 60000
  maximum-pool-size: 5

hello:
  binary-log:
    host: localhost
    port: 3307
    user: repl
    password: slavepass
  meta:
    available-tables:
      DEP:
        - "NO"
      DEP2:
        - "NO"
        - "NAME"