version: '2'
services:
  zookeeper:
    image: freestrings/zookeeper
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    environment:
      ZK_MYID: 1
      ZK_DATA_DIR: /zookeeper
    volumes:
      - ./zookeeper:/zookeeper
  kafka1:
    image: freestrings/kafka
    ports:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - ./kafka1:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: freestrings/kafka
    ports:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - ./kafka2:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: freestrings/kafka
    ports:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - ./kafka3:/kafka
      - /var/run/docker.sock:/var/run/docker.sock