version: '3'
services:
  mysql-master:
    image: mysql:8.0.21
    restart: always
    volumes:
      - ./db:/db
      - ./seeding.sh:/docker-entrypoint-initdb.d/seeding.sh
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"
    ports:
      - "33060:3306"
  mysql-slave:
    image: mysql:8.0.21
    volumes:
      - ./db:/db
      - ./seeding.sh:/docker-entrypoint-initdb.d/seeding.sh
      - ./mysql/conf-slave:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testa
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 1234
      TZ: "Asia/Seoul"
    ports:
      - "33061:3306"