spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testa
    username: user
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql: trace
    org.springframework.transaction: trace