version: "3.8"

services:
  
  api-otel:
    image: azul/zulu-openjdk-alpine:11
    network_mode: "host"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:8006
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=none
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_RESOURCE_ATTRIBUTES=service.name=api-otel
      - |
        JAVA_OPTS_APPEND=
        -Dotel.javaagent.debug=true
    volumes:
      - ./data/logs/api-otel-collector:/app/logs
      - ./api/build/libs/api-0.0.1-SNAPSHOT.jar:/app.jar
      - ./api/scripts/start-app.sh:/start-app.sh
      - ./api/agent/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    command: ["sh", "/start-app.sh"]

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   network_mode: "host"
  #   volumes:
  #     - ./etc/otel-collector-loki.yaml:/etc/otel-config.yaml
  #   links:
  #     - loki
  #   command: [
  #     "--config=/etc/otel-config.yaml"
  #   ]
    
  loki:
    image: grafana/loki:2.7.3
    network_mode: "host"
    command: -config.file=/etc/loki/local-config.yaml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    network_mode: "host"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    network_mode: "host"
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    depends_on:
      - elasticsearch
    
  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:7.4.0-ubuntu
    network_mode: "host"
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    links:
      - loki
    depends_on:
      - prometheus
