version: '3'
services:
  mysql1:
    image: mysql:8.0.21
    restart: always
    volumes:
      - ./db:/db
      - ./seeding.sh:/docker-entrypoint-initdb.d/seeding.sh
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
  mysql2:
    image: mysql:8.0.21
    restart: always
    volumes:
      - ./db:/db
      - ./seeding.sh:/docker-entrypoint-initdb.d/seeding.sh
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"
    ports:
      - "3307:3306"