spring:
  datasource:
    url: jdbc:mysql://mysql:3306/testa
    username: user
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081

#logging.level.org.hibernate: TRACE