spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:mysql://localhost:3307/testa
    username: user
    password: 1111
    driverClassName: com.mysql.jdbc.Driver

  batch:
    initialize-schema: always
    job.enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#logging.level.root: DEBUG