[package]
name = "tetris"
version = "0.1.0"
authors = ["freestrings <freestrings@gmail.com>"]

[dependencies]
sdl2 = "0.30"
rand = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
emscripten-sys = "0.3"
