spring.batch:
  # 어플리케이션이 뜨면서 바로 배치가 실행되는 것을 방지
  job.enabled: false

fs:
  outbound:
    protocol: http
    host: 104.198.209.68
    port: 9100
    path: ""
    user: "personal_sc"
    password: "personal_sc!2#"
  batch:
      schedule:
        praha: "* 5 * * * *"
        prahaMemberActionCntInInfos: "* 5 * * * *"