version: '3.2'

services:

  mysql-meta:
    image: mysql
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"

#  rabbitmq:9090

#    image: rabbitmq:management
#    ports:
#    - "5672:5672"
#    - "15672:15672"
#  mysql-data:
#    image: mysql
#    restart: always
#    ports:
#    - 3308:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#    volumes:
#    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
