version: '3.2'

services:

  mysql-meta:
    image: mysql
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

#  mysql-data:
#    image: mysql
#    restart: always
#    ports:
#    - 3308:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#    volumes:
#    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
