version: '3.2'

services:

  mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  web1:
    image: fs.playground/kotlin-optimistic-lock:0.0.1-SNAPSHOT
    ports:
      - 8081:8080
    depends_on:
      - mysql
#    links:
#      - mysql

#  web2:
#    image: fs.playground/kotlin-optimistic-lock:0.0.1-SNAPSHOT
#    ports:
#      - 8082:8080
#    depends_on:
#      - mysql
#    links:
#      - mysql
#
#  web3:
#    image: fs.playground/kotlin-optimistic-lock:0.0.1-SNAPSHOT
#    ports:
#      - 8083:8080
#    depends_on:
#      - mysql
#    links:
#      - mysql

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
#    links:
#      - web1
#      - web2
#      - web3
