version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql