spring:
  application:
    name: zuulserver

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true

server.tomcat.accesslog:
  enabled: true
  directory: /tmp/logs