version: '3'

services:
  dnsmasq:
    image: andyshinn/dnsmasq:latest
    cap_add:
      - NET_ADMIN
    command: "--no-daemon --log-queries"
    networks:
      static-network:
        ipv4_address: 172.16.0.53
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq.hosts:/etc/dnsmasq.hosts
  squid:
    image: sameersbn/squid:3.5.27
    ports:
      - "3128:3128"
    volumes:
      - "./squid/cache:/var/spool/squid"
      - "./squid.conf:/etc/squid/squid.conf"
    dns:
      - 172.16.0.53
    depends_on:
      - "wait-for-dnsmasq"
    networks:
      static-network:
        ipv4_address: 172.16.0.2
  wait-for-dnsmasq:
    image: busybox
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
    command: ["/wait-for-it.sh", "dnsmasq:53"]
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.16.0.0/16
