[package]
name = "rtag"
version = "0.1.0"
authors = ["freestrings@wemakeprice.com"]
links = "id3v2"
build = "build.rs"

[dependencies]
libc = "0.2.0"

[build-dependencies]
git2 = { git = "https://github.com/alexcrichton/git2-rs.git" }